### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub-modules-gallery#17]
Declaration of `humhub\modules\gallery\controllers\MediaController::actionEdit($itemId, $openGalleryId = NULL, $fromWall = false)` should be compatible with `humhub\modules\gallery\controllers\CustomGalleryController::actionEdit($itemId = NULL, $visibility = humhub\modules\content\models\Content::VISIBILITY_PRIVATE)` in `/protected/modules/gallery/controllers/MediaController.php` on line 62

**Comment by arnfinnkristensen** [comment]
I am getting the same error when i type yii help when the gallery module is activated. To avoid this error I have to deactivate the gallery modul, but that is not a good solution.

I am currently using humhub version 1.2.1 and gallery version 1.0.2.

Here is my command with corresponding output to console:

```
C:\inetpub\wwwroot\protected>yii help
PHP Warning 'yii\base\ErrorException' with message 'Declaration of humhub\modules\gallery\controllers\MediaController::actionEdit($itemId, $openGalleryId = NULL, $fromWall = false) should be compatible with humhub\modules\gallery\controllers\CustomGalleryController::actionEdit($itemId = NULL, $visibility = humhub\modules\content\models\Content::VISIBILITY_PRIVATE)'

in C:\inetpub\wwwroot\protected\modules\gallery\controllers\MediaController.php:62

Stack trace:
#0 C:\inetpub\wwwroot\protected\vendor\yiisoft\yii2\BaseYii.php(292): yii\base\ErrorHandler->handleError(2, 'Declaration of ...', 'C:\\inetpub\\wwwr...', 62, Array)
#1 C:\inetpub\wwwroot\protected\vendor\yiisoft\yii2\BaseYii.php(292): include()
#2 [internal function]: yii\BaseYii::autoload('humhub\\modules\\...')
#3 [internal function]: spl_autoload_call('humhub\\modules\\...')
#4 C:\inetpub\wwwroot\protected\vendor\yiisoft\yii2\console\controllers\HelpController.php(275): class_exists('humhub\\modules\\...')
#5 C:\inetpub\wwwroot\protected\vendor\yiisoft\yii2\console\controllers\HelpController.php(258): yii\console\controllers\HelpController->validateControllerClass('humhub\\modules\\...')
#6 C:\inetpub\wwwroot\protected\vendor\yiisoft\yii2\console\controllers\HelpController.php(247): yii\console\controllers\HelpController->getModuleCommands(Object(humhub\modules\gallery\Module))
#7 C:\inetpub\wwwroot\protected\vendor\yiisoft\yii2\console\controllers\HelpController.php(181): yii\console\controllers\HelpController->getModuleCommands(Object(humhub\components\console\Application))
#8 C:\inetpub\wwwroot\protected\vendor\yiisoft\yii2\console\controllers\HelpController.php(193): yii\console\controllers\HelpController->getCommands()
#9 C:\inetpub\wwwroot\protected\vendor\yiisoft\yii2\console\controllers\HelpController.php(288): yii\console\controllers\HelpController->getCommandDescriptions()
#10 C:\inetpub\wwwroot\protected\vendor\yiisoft\yii2\console\controllers\HelpController.php(67): yii\console\controllers\HelpController->getDefaultHelp()
#11 [internal function]: yii\console\controllers\HelpController->actionIndex(NULL)
#12 C:\inetpub\wwwroot\protected\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#13 C:\inetpub\wwwroot\protected\vendor\yiisoft\yii2\base\Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#14 C:\inetpub\wwwroot\protected\vendor\yiisoft\yii2\console\Controller.php(128): yii\base\Controller->runAction('', Array)
#15 C:\inetpub\wwwroot\protected\vendor\yiisoft\yii2\base\Module.php(523): yii\console\Controller->runAction('', Array)
#16 C:\inetpub\wwwroot\protected\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('help', Array)
#17 C:\inetpub\wwwroot\protected\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction('help', Array)
#18 C:\inetpub\wwwroot\protected\vendor\yiisoft\yii2\base\Application.php(380): yii\console\Application->handleRequest(Object(yii\console\Request))
#19 C:\inetpub\wwwroot\protected\yii(29): yii\base\Application->run()
#20 {main}
```

**Comment by kristianlm** [comment]
Note that this is now adressed in 406f98f6b0d625ffe1a947bda788666196cb361f. Testing time!
